Repository Baghdad-Squad/Tudee, pull requests merged in 2025-06, with the labels that each got.

#80 Add koin setup
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/baghdad/tudee/app/TudeeApplication.kt
  app/src/main/java/com/baghdad/tudee/di/.gitkeep
  app/src/main/java/com/baghdad/tudee/di/ServiceModule.kt
  app/src/main/java/com/baghdad/tudee/di/ViewModelModule.kt
  gradle/libs.versions.toml
Labels: Priority: HIGH

#77 Feature/day night switch
  app/src/main/java/com/baghdad/tudee/ui/composable/dayNightSwitch/CloudCircles.kt
  app/src/main/java/com/baghdad/tudee/ui/composable/dayNightSwitch/DayNightSwitch.kt
  app/src/main/java/com/baghdad/tudee/ui/composable/dayNightSwitch/FadedMoonCircles.kt
  app/src/main/java/com/baghdad/tudee/ui/composable/dayNightSwitch/MoonCircleToCloudCircle.kt
  app/src/main/java/com/baghdad/tudee/ui/composable/dayNightSwitch/NightStars.kt
  app/src/main/java/com/baghdad/tudee/ui/composable/dayNightSwitch/RadialGradientCircle.kt
  app/src/main/java/com/baghdad/tudee/ui/utils/extension.kt
  app/src/main/res/drawable/moon.png
  app/src/main/res/drawable/sun.png
  app/src/main/res/drawable/vector.xml
Labels: Priority: HIGH

#97 Feature/category image types
  app/src/main/java/com/baghdad/tudee/app/TudeeApplication.kt
  app/src/main/java/com/baghdad/tudee/data/mapper/CategoryMapper.kt
  app/src/main/java/com/baghdad/tudee/data/model/CategoryDto.kt
  app/src/main/java/com/baghdad/tudee/data/service/CategoryServiceImpl.kt
  app/src/main/java/com/baghdad/tudee/data/source/PredefinedCategorySource.kt
  app/src/main/java/com/baghdad/tudee/data/source/PredefinedCategorySourceImpl.kt
  app/src/main/java/com/baghdad/tudee/di/DataSourceModule.kt
  app/src/main/java/com/baghdad/tudee/domain/entity/Category.kt
Labels: Priority: HIGH

#184 Task count chip in home does not perform any action and count number is fixed
  app/src/main/java/com/baghdad/tudee/ui/navigation/NavHostApp.kt
  app/src/main/java/com/baghdad/tudee/ui/screens/homeScreen/HomeScreen.kt
  app/src/main/res/values/strings.xml
Labels: bug

#175 Fix/DeleteTaskBottomSheet in tasks screen doesn't open
  app/src/main/java/com/baghdad/tudee/ui/composable/delete_item/DeleteTaskBottomSheet.kt
  app/src/main/java/com/baghdad/tudee/ui/screens/tasks/TasksScreen.kt
  app/src/main/java/com/baghdad/tudee/ui/screens/tasks/components/SwipeToDeleteCard.kt
Labels: bug

#268 Fix/categories screen categories list padding
  app/src/main/java/com/baghdad/tudee/ui/screens/categories/component/CategoriesList.kt
Labels: Priority: HIGH

#285 Refactor/category tasks screen
  app/src/main/java/com/baghdad/tudee/ui/base/BaseViewModel.kt
  app/src/main/java/com/baghdad/tudee/ui/composable/delete_item/DeleteCategoryBottomSheet.kt
  app/src/main/java/com/baghdad/tudee/ui/screens/categories/CategoriesScreen.kt
  app/src/main/java/com/baghdad/tudee/ui/screens/categoryTasksScreen/CategoriesTasksInteractionListener.kt
  app/src/main/java/com/baghdad/tudee/ui/screens/categoryTasksScreen/CategoryTasksScreen.kt
  app/src/main/java/com/baghdad/tudee/ui/screens/categoryTasksScreen/CategoryTasksScreenEffect.kt
  app/src/main/java/com/baghdad/tudee/ui/screens/categoryTasksScreen/CategoryTasksScreenUiState.kt
  app/src/main/java/com/baghdad/tudee/ui/screens/categoryTasksScreen/CategoryTasksViewModel.kt
  app/src/main/java/com/baghdad/tudee/ui/screens/categoryTasksScreen/components/CategoryTasksList.kt
  app/src/main/java/com/baghdad/tudee/ui/screens/categoryTasksScreen/components/CategoryTasksPager.kt
  app/src/main/java/com/baghdad/tudee/ui/screens/categoryTasksScreen/components/CategoryTasksScreenHeader.kt
  app/src/main/java/com/baghdad/tudee/ui/screens/categoryTasksScreen/components/CategoryTasksTabs.kt
  app/src/main/java/com/baghdad/tudee/ui/screens/categoryTasksScreen/components/IconInBox.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values/strings.xml
Labels: Priority: HIGH

#283 fix wrong action buttons padding in data picker
  app/src/main/java/com/baghdad/tudee/ui/composable/dateYearDialog/DialogActionButtons.kt
Labels: bug, Priority: HIGH

#280 refactor main activity
  app/src/main/java/com/baghdad/tudee/ui/main/AppContent.kt
  app/src/main/java/com/baghdad/tudee/ui/main/MainActivity.kt
  app/src/main/java/com/baghdad/tudee/ui/main/MainScreen.kt
  app/src/main/java/com/baghdad/tudee/ui/navigation/NavHostApp.kt
  app/src/main/java/com/baghdad/tudee/ui/navigation/NavigationContent.kt
  app/src/main/java/com/baghdad/tudee/ui/navigation/StartDestination.kt
Labels: Priority: HIGH
